---
- name: Backup Linux Servers
  hosts: all
  become: true
  ignore_errors: true
  ignore_unreachable: true
  gather_facts: false
  vars:
    backup_dest: "/root/backup/"
    folders_to_backup:
      - "/etc/"
      - "/var/log/"
      - "/home/"
    
  pre_tasks:
    - name: Init
      ansible.builtin.debug:
        msg: "Starting ..."

  tasks:
    - name: Create backup directory
      ansible.builtin.shell:
        cmd: "mkdir -p {{ backup_dest }}"
    
    - name: Make a security copy
      ansible.builtin.shell:
        cmd: "tar -czf {{ backup_dest }}/backup_{{ ansible_date_time.date }}.tar.gz -C {{ folders_to_backup[0] }} {{ folders_to_backup[1] }} {{ folders_to_backup[2] }}"

  post_tasks:
    - name: Finish
      ansible.builtin.debug:
        msg: "Ending ..."
